# Generated by Django 6.0.2 on 2026-07-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_profile_section_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
