# Generated by Django 6.0.2 on 2026-07-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_academic_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
    ]
