# Generated by Django 6.0.2 on 2026-03-02 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='assigned_by',
            field=models.ForeignKey(limit_choices_to={'role': 'registrar'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='courses.course'),
        ),
    ]
