# Generated by Django 6.0.2 on 2026-07-07 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_is_draft'),
        ('courses', '0005_alter_department_options_alter_program_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='courses.academicyear'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='courses.section'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='courses.semester'),
        ),
    ]
